# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0 filetype=yaml:
#
# This CI uses the freedesktop.org ci-templates.
# Please see the ci-templates documentation for details:
# https://freedesktop.pages.freedesktop.org/ci-templates/

.templates_sha: &template_sha ef5e4669b7500834a17ffe9277e15fbb6d977fff # see https://docs.gitlab.com/ee/ci/yaml/#includefile

# FDO_DISTRIBUTION_TAG is the tag of the docker image used for the build jobs.
# If the image doesn't exist yet, the docker-image stage generates it.
#
# In order to generate a new image, one should generally change the tag.
# While removing the image from the registry would also work, that's not
# recommended except for ephemeral images during development: Replacing an
# image after a significant amount of time might pull in newer versions of
# gcc/clang or other packages, which might break the build with older commits
# using the same tag.
variables:
    FDO_UPSTREAM_REPO:    'xorg/xserver'
    MESON_BUILDDIR:       'build'
    REPO_URL_XORGPROTO:   'https://gitlab.freedesktop.org/xorg/proto/xorgproto.git'
    XORG_DEBIAN_VERSION:  'bullseye-slim'
    XORG_DEBIAN_EXEC:     'env FDO_CI_CONCURRENT=${FDO_CI_CONCURRENT} bash .gitlab-ci/debian-install.sh'
    XORG_DEBIAN_TAG:      '2025-03-04-no-xorg'

include:
  - project: 'freedesktop/ci-templates'
    ref: *template_sha
    file:
      - '/templates/debian.yml'
      - '/templates/ci-fairy.yml'
  - template: Security/SAST.gitlab-ci.yml

stages:
    - docker-image
    - build-and-test
    - test

.ci-run-policy:
  # Retry jobs after runner system failures
  retry:
    max: 2
    when:
      - runner_system_failure
  # Cancel CI run if a newer commit is pushed to the same branch
  interruptible: true

.debian:
  variables:
    FDO_DISTRIBUTION_VERSION:   '$XORG_DEBIAN_VERSION'
    FDO_DISTRIBUTION_EXEC:      '$XORG_DEBIAN_EXEC'
    FDO_DISTRIBUTION_TAG:       '$XORG_DEBIAN_TAG'

debian-bullseye:
  extends:
    - .fdo.container-build@debian
    - .ci-run-policy
    - .debian
  stage: docker-image
  variables:
    GIT_STRATEGY: none

.xorg-image@debian:
    extends:
        - .fdo.distribution-image@debian
        - .debian

.common-build-and-test:
    extends:
        - .xorg-image@debian
        - .ci-run-policy
    stage: build-and-test
    artifacts:
        when: always
        paths:
            - $MESON_BUILDDIR/meson-logs/
            - $MESON_BUILDDIR/test/piglit-results/
    variables:
        MESON_ARGS: -Dc_args="-fno-common" -Dprefix=/usr -Dwerror=true -Dxcsecurity=true
        CCACHE_COMPILERCHECK: content
        CCACHE_DIR: /cache/xserver/cache
        LC_ALL: C.UTF-8
    before_script:
        - export CCACHE_BASEDIR="$PWD"
        - export PATH="/usr/lib/ccache:$PATH"
        - ccache --show-stats
    after_script:
        - ccache --show-stats

meson:
    extends: .common-build-and-test
    script:
        - .gitlab-ci/meson-build.sh --run-test
        - .gitlab-ci/check-piglit-results.sh
        - .gitlab-ci/manpages-check
        - .gitlab-ci/check-ddx-build.sh
    variables:
      XTEST_DIR: /root/xts
      PIGLIT_DIR: /root/piglit
      LP_NUM_THREADS: 0
      MESON_DDX_BUILD_ARGS: >
        -Dxwayland=${BUILD_XWAYLAND} -Dxvfb=${BUILD_XVFB}
      BUILD_XVFB: true
      BUILD_XWAYLAND: true
      MESON_EXTRA_ARGS: ${MESON_DDX_BUILD_ARGS}

meson-enable-options:
    extends: meson
    variables:
        MESON_EXTRA_ARGS: --auto-features=enabled -Dlisten_tcp=true -Dxf86bigfont=true -Dxcsecurity=true -Ddri3=true -Dlibunwind=true ${MESON_DDX_BUILD_ARGS}

meson-disable-options:
    extends: meson
    variables:
        MESON_EXTRA_ARGS: --auto-features=disabled -Dglamor=false -Dglx=false -Dxdmcp=false -Dxdm-auth-1=false -Dxace=false -Dxcsecurity=false -Dxinerama=false -Dxv=false -Ddrm=false -Ddri3=false ${MESON_DDX_BUILD_ARGS}

meson-noglamor:
    extends: meson
    variables:
        MESON_EXTRA_ARGS: -Dglamor=false ${MESON_DDX_BUILD_ARGS}

xwayland-nolibdecor:
    extends: meson
    variables:
        BUILD_XVFB: false
        MESON_EXTRA_ARGS: -Dlibdecor=false ${MESON_DDX_BUILD_ARGS}

meson-dist:
    extends: .common-build-and-test
    artifacts:
        when: always
        paths:
            - $MESON_BUILDDIR/meson-logs/
            - $MESON_BUILDDIR/xserver-*/$MESON_BUILDDIR/meson-logs/
            - xserver-tarball/install/
    script:
        - .gitlab-ci/meson-build.sh --run-dist
        - mkdir xserver-tarball
        - tar xf $MESON_BUILDDIR/meson-dist/xserver-*.tar.xz -C xserver-tarball --strip-components=1
        - .gitlab-ci/meson-build.sh -C xserver-tarball --skip-test --skip-dist --run-install
    variables:
      MESON_DIST_ARGS: --no-tests
      MESON_EXTRA_ARGS: -Dprefix=$CI_PROJECT_DIR/xserver-tarball/install/

#
# Verify that commit messages are as expected
#
check-commits:
  extends:
    - .fdo.ci-fairy
  needs: []
  stage: test
  script:
    - ci-fairy check-commits --junit-xml=results.xml
  except:
    - main@xorg/xserver
  variables:
    GIT_DEPTH: 100
  artifacts:
    reports:
      junit: results.xml
  allow_failure: true

check-whitespace:
  extends:
    - .fdo.ci-fairy
  stage: test
  script:
    - .gitlab-ci/whitespace-check.py $(git ls-files hw/xwayland)

#
# Workflow rules needed due to:
# https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/438
#
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_PIPELINE_SOURCE == 'push'
